/*
	BioAssay Express (BAE)

	Copyright 2016-2023 Collaborative Drug Discovery, Inc.

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

		http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/

package com.cdd.bae.rest.eln;

import com.cdd.bae.config.*;
import com.cdd.bae.config.authentication.Authentication.*;
import com.cdd.bae.data.*;
import com.cdd.bae.rest.*;
import com.cdd.bao.template.*;

import org.json.*;

/*
	AutogeneratedText (Common assay template supported)
	
	Parameters:
		assignment
			propURI
			list of annotations (objects with valueURI)
		... 
		
	Return:
		text: autogenerated text
*/

public class AutogeneratedText extends RESTBaseServlet
{
	private static final long serialVersionUID = 1L;

	// ------------ public methods ------------

	@Override
	protected JSONObject processRequest(JSONObject input, Session session) throws RESTException
	{
		Schema schema = Common.getSchemaCAT();
		String block = input.optString("block", "ELN");
		Transliteration.Boilerplate boiler = Common.getTransliteration().getBoilerplateBlock(schema.getSchemaPrefix(), block);

		DataObject.Assay assay = TransliterateAssay.convertToAssay(input);
		
		return new JSONObject(input, JSONObject.getNames(input))
				.put("text", TransliterateAssay.transcribeAssay(boiler, schema, assay));
	}
}
